# Dice Simulation

JMA July 2024

A simulation based on Kelly-investment strategy to demonstrate sequential hedging and risk taking

In [1]:
import pickle
from pathlib import Path
import numpy as np
from numpy.random import default_rng
import pandas as pd
import seaborn as sns

from bokeh.plotting import figure, show
from bokeh.layouts import column, row
from bokeh.models import ColumnDataSource, VBar, Span
from bokeh.io import output_notebook
output_notebook()

rng = default_rng(seed=101)

DICE_SIDES = 60
DICE_THRESHOLD = 36 
OCTAVES = [pow(2, k) for k in range(1,10)]
NUM_PERIODS = OCTAVES[-1]
WIN_BETA_PRIORS = {"a": DICE_THRESHOLD, "b":(DICE_SIDES-DICE_THRESHOLD)}
SIMULATION_COUNT = 1000
PKL_FILENAME = f'trajectories_{NUM_PERIODS}_by_{SIMULATION_COUNT}.pkl'

In [2]:
OCTAVES

[2, 4, 8, 16, 32, 64, 128, 256, 512]

In [3]:
def beta_mean(beta):
    return beta['a']/(beta['a'] + beta['b'])

def fair_win_probability(sides=DICE_SIDES, win_thresh= DICE_THRESHOLD):
    "Probability of a winning investment"
    fair_win = win_thresh / sides
    return fair_win

fair_win_p = fair_win_probability()
f'True probability of an investment win: {fair_win_p:.3},  Prior {beta_mean(WIN_BETA_PRIORS):.3}'

'True probability of an investment win: 0.6,  Prior 0.6'

In [ ]:
def win_prob_estimate(win_or_loss, priors):
    'Assume a beta distribution. Do an update for a binomial process'
    if win_or_loss == 1:
        priors['a'] +=1
    else:
        priors['b'] +=1
    beta_mean = priors['a'] /(priors['a']+ priors['b'])
    return beta_mean, priors

def investment_process(true_win_p, rounds=NUM_PERIODS-1):
    'A sequence of 1s and 0s, with win == 1, loss = 0. For the true win stochastic process.'
    return rng.binomial(1, true_win_p, rounds)

def beta_update(wins, prior=WIN_BETA_PRIORS, rounds=NUM_PERIODS-1):
    'For the unobserved actual win sequence  compute the observed, estimated win prob update.'
    win_estimates = np.zeros(rounds)
    for k, a_win in enumerate(wins):
        win_estimates[k], prior = win_prob_estimate(a_win, prior)
    return win_estimates, prior
    
wins = investment_process(fair_win_p)
win_p_estimates, prior = beta_update(wins)
f'Beta parameters: {prior}, mean: {beta_mean(prior):.4}'

"Beta parameters: {'a': 350, 'b': 221}, mean: 0.613"

In [5]:
def kelly_rule(p):
    'The fraction to bet for an assumed win probability'
    # This works as a vectorized function 
    return ((2*p - 1) * (p > 0.5))


def log_wealth_trajectory(wins, win_p_estimate):
    """
    Use the estimated win probability update as the bet fraction, using the Kelly rule
    """
    # The log increment for a win is different than for a loss -- is that a problem? 
    log_inc = np.log(1+ (2*wins-1) * kelly_rule(win_p_estimate))
    trajectory = np.cumsum(log_inc)
    #  Start at 0
    trajectory = np.insert(trajectory, 0, 0)
    return trajectory

In [6]:
estimate_cds = ColumnDataSource(pd.DataFrame({'estimate': win_p_estimates}).reset_index())
pb= figure(
        title="Running Bayes estimate of win probability. ",
        y_range=(min(0.98 *fair_win_p, np.min(win_p_estimates)), max(1.02 *fair_win_p, np.max(win_p_estimates))),
        width = 900, height = 480)
pb.line(x='index', y='estimate', source=estimate_cds)
actual_p = Span(location=fair_win_p, dimension='width', line_dash='dotdash')
pb.renderers.extend([actual_p])

In [7]:
a_trajectory = log_wealth_trajectory(wins, win_p_estimates)
trajectory_cds = ColumnDataSource(pd.DataFrame({'trajectory': a_trajectory}).reset_index())
pt= figure(
        title="Log value over multiple rounds. ",
        #y_range=(min(0.98 *fair_win_p, np.min(win_p_estimate[0])), max(1.02 *fair_win_p, np.max(win_p_estimate[0]))),
        width = 900, height = 480)
pt.line(x='index', y='trajectory', source=trajectory_cds, line_color='darkred')
# actual_p = Span(location=fair_win_p, dimension='width', line_dash='dotdash')
# p.renderers.extend([actual_p])
show(column(pb,pt))

In [8]:



# Careful to reset the prior for each simulation
def run_simulations(fair_win_p, prior=WIN_BETA_PRIORS, simulations=SIMULATION_COUNT):
    """ 
"""
    trajectories = np.zeros((NUM_PERIODS, simulations ))
    for a_sim in range(simulations):
        wins = investment_process(fair_win_p)
        win_p_estimates, prior =beta_update(wins, prior)
        a_trajectory = log_wealth_trajectory(wins, win_p_estimates)
        print('.', end='')
        trajectories[:,a_sim] = a_trajectory

    return trajectories

In [9]:
#SIMULATION_COUNT = 10
simulated_trajectories = pd.DataFrame(run_simulations(fair_win_p, simulations=SIMULATION_COUNT))
simulated_trajectories.head()

........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.204794,0.197897,0.200557,0.196473,0.179387,0.183813,-0.221221,0.180150,0.175503,0.173386,...,0.180720,0.180740,0.180720,-0.220725,0.180752,0.180689,0.180630,-0.220630,-0.220591,0.180616
2,0.410687,0.396385,0.401512,0.393251,-0.038802,0.367838,-0.040000,0.360462,0.351151,0.346904,...,-0.040023,-0.040033,0.361440,-0.441447,-0.040039,0.361379,0.361261,-0.039986,-0.039973,0.361233
3,0.617673,0.595462,0.150735,0.148761,0.140459,0.552075,0.141406,0.540934,0.138251,0.137106,...,-0.260764,-0.260802,0.140696,-0.260742,-0.260826,0.542071,0.541893,-0.260616,-0.260563,0.140644
4,0.825747,0.795128,-0.099060,0.345370,0.319977,0.326533,0.322995,0.721569,-0.074333,-0.072408,...,-0.481501,-0.481569,-0.080045,-0.080035,-0.481611,0.722764,0.321281,-0.481242,-0.079946,-0.079943

In [10]:
simulated_trajectories.describe()

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
count,512.000000,512.000000,512.000000,512.000000,512.000000,512.000000,512.000000,512.000000,512.000000,512.000000,...,512.000000,512.000000,512.000000,512.000000,512.000000,512.000000,512.000000,512.000000,512.000000,512.000000
mean,6.590240,9.299672,4.635034,0.813821,5.203608,3.527961,3.565771,3.218096,1.283490,6.287744,...,4.032105,1.493094,5.700706,7.046251,1.721011,2.166776,8.225597,3.660394,4.080532,6.368697
std,3.791796,4.393543,3.388955,1.471412,3.854981,2.625620,2.226227,2.172279,2.906493,3.829399,...,3.187342,2.206204,2.878137,5.106375,1.436239,1.436740,4.769095,1.927893,2.731144,3.064743
min,0.000000,0.000000,-0.620348,-1.716589,-0.117995,-0.806883,-0.340677,-2.338594,-4.123248,-0.317711,...,-0.901076,-1.739243,-1.203087,-0.700906,-0.982634,-1.480073,-0.721038,-0.481242,-0.460420,-1.061421
25%,2.682541,4.744711,1.217887,-0.281606,1.301325,1.582840,1.225540,1.724449,-1.528055,3.792023,...,1.407983,-0.046171,3.785241,1.935634,0.402508,1.639459,3.790515,2.110821,1.944034,5.034692
50%,6.765790,10.112155,4.838696,0.580701,4.902052,2.303110,3.930810,4.195590,1.772328,5.910099,...,3.384104,0.752580,7.024696,6.709801,1.529272,2.608174,7.612170,3.951318,2.848539,6.220400
75%,9.585640,13.386205,6.466102,1.582193,8.580403,5.950369,4.838877,4.799693,3.562136,8.876859,...,5.521657,2.532204,7.871585,12.610272,2.993623,3.128861,12.247989,5.001600,6.786818,8.355058
max,13.277907,15.681184,11.837784,4.924121,13.669473,9.104525,9.028132,6.090164,7.211823,14.388434,...,12.938395,7.638973,9.212304,15.507472,4.695094,4.888476,15.902073,7.137038,9.846568,11.469258

In [11]:
# Define 2 std limits for trajectories.
def std_dev_limits(slice, limit_fraction = 0.05):
    h_bar, h_edges = np.histogram(slice, bins = 100, density=True)
    h_cum_bar = np.cumsum(h_bar *(h_edges[1] - h_edges[0]))
    edges = h_edges[:-1]   # better to use the midpoints
    hist_lower_mask = h_cum_bar < limit_fraction 
    if sum(hist_lower_mask) == 0:     # No bars below the limit
        lower = edges[0]
    else:
        lower = edges[hist_lower_mask][-1]
    hist_upper_mask = h_cum_bar > 1-limit_fraction 
    if sum(hist_upper_mask) == 0:
        upper = edges[-1]
    else:
        upper = edges[hist_upper_mask][0]
    mid = edges[h_cum_bar <=0.5][-1]
    return lower, mid, upper

trajectory_extremes = pd.DataFrame(None, columns=['lower', 'mid', 'upper'])
trajectory_extremes.loc[1] = (0,0,0)
for octave in OCTAVES:
    print(octave, end='\t')
    trajectory_extremes.loc[octave] = std_dev_limits(simulated_trajectories.iloc[octave-1,:])

2	4	8	16	32	64	128	256	512

In [12]:

# The lower, mid and upper quantiles
te_src = ColumnDataSource(trajectory_extremes.reset_index())

# Plot just some of the trajectories. 
some_trajectories = np.random.choice(range(SIMULATION_COUNT), 20, replace=False)
# Every 16th point leaves 256 points
sub_samples = list(range(0,OCTAVES[-1], OCTAVES[0]))

p= figure(
    title= f"Selected Trajectories, P(win)= {fair_win_p:.3} ",
    width = 1000, height = 600, 
    background_fill_color="#fafafa",
    # x_axis_type="log",
    x_axis_label = 'Run length',
    y_axis_label = 'Accumulated wealth proportion')

# Downsample the trajectories for efficiency plotting. 
short_trajectories = simulated_trajectories.loc[sub_samples, :]
sim_df = pd.DataFrame(short_trajectories.loc[:, some_trajectories], index = sub_samples)

sim_df.columns = [str(k) for k in sim_df.columns]
sim_src = ColumnDataSource(sim_df)
for k in sim_df.columns:
    p.line(x='index', y=str(k), source=sim_src, line_alpha=0.4, line_color='grey')

p.line(x='index', y='lower', color='red', line_dash='dashed', line_width = 3, source=te_src)
p.line(x='index', y='mid', color='blue', line_width = 3, source=te_src)
p.line(x='index', y='upper', color='red', line_dash='dashed', line_width = 3, source=te_src)


    

show(p)

In [13]:
def bokeh_hist(sample, x_range, title= '', bin_ct=30):
    'Return a graphic histogram object'
    # Find the range of all samples. 
    fig = figure(width= 380, height=360,  title=title, x_range=x_range )
    bars, bin_edges = np.histogram(sample, bins=bin_ct)
    # Split into below and above zero. 
    neg_bin_edges = bin_edges[bin_edges <= 0]
    pos_bin_edges = bin_edges[len(neg_bin_edges):]
    neg_bars = bars[:len(neg_bin_edges)]
    pos_bars = bars[len(neg_bin_edges):]
    neg_bin_edges  = np.append(neg_bin_edges, pos_bin_edges[0])
    LINE_ARGS = dict(line_color=None)
    # Define the sides of each "box" in the histogram plot
    fig.quad(bottom=0, left=neg_bin_edges[:-1], right=neg_bin_edges[1:], top=neg_bars, color='purple', **LINE_ARGS)
    fig.quad(bottom=0, left=pos_bin_edges[:-1], right=pos_bin_edges[1:], top=pos_bars, color='limegreen', **LINE_ARGS)
    return fig

In [14]:
figures = []
xmin, xmax = simulated_trajectories.min(), simulated_trajectories.max()
for octave in OCTAVES:
    figures.append(bokeh_hist(simulated_trajectories[octave-1,:], x_range=(xmin, xmax), title= f'{octave} runs'))
show(column(row(*figures[:2]), 
            row(*figures[2:4]),
            row(*figures[4:6]),
            row(*figures[6:8]),
            row(*figures[8:10]),
            row(*figures[10:])))

KeyError: (1, slice(None, None, None))

In [ ]:

if not Path(PKL_FILENAME).exists():
    pickle.dump(simulated_trajectories, open(PKL_FILENAME, 'wb'))
else:
    results = pickle.load(open(PKL_FILENAME, 'rb'))